/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Fabrizzio Ontaneda
 */
public class FurbalandiaCronometroHombre extends javax.swing.JFrame {

    /**
     * Creates new form Cronometro
     */
    //Creamos las variables del tiempo
    private Timer tiempo;
    private int segundos = 59;
    private int minutos = 4;

    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            segundos--;
            if (minutos == 0 && segundos == 0) {
                tiempo.stop();
                segundos = 0;
                minutos = 0;
                FurbalandiaCuentasNiño fcn=new FurbalandiaCuentasNiño();
                fcn.setVisible(true);
                System.out.println("Se acabó el tiempo");
                cerrarPrograma();
            }
            if (segundos == 00) {
                minutos--;
                segundos = 59;
            }

            actualizarEtiquetaTiempo();
        }
    };

    
    public void cerrarPrograma(){
        this.dispose();
    }
    
    
    private void actualizarEtiquetaTiempo() {
        String texto = (minutos <= 9 ? "0" : "") + minutos + ":" + (segundos <= 9 ? "0" : "") + segundos;
        etiqueta_tiempo.setText(texto);
    }

    //constructor
    public FurbalandiaCronometroHombre() {
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Cronometro");
        //OJO AQUÍ
        tiempo = new Timer(100, acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIniciar = new javax.swing.JButton();
        etiqueta_tiempo = new javax.swing.JLabel();
        lWallPaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonIniciar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        botonIniciar.setText("Iniciar");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(botonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 150, 60));

        etiqueta_tiempo.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        etiqueta_tiempo.setForeground(new java.awt.Color(255, 255, 255));
        etiqueta_tiempo.setText("05:00");
        getContentPane().add(etiqueta_tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        lWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/niñoReloj.png"))); // NOI18N
        lWallPaper.setText(" ");
        getContentPane().add(lWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 697, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        tiempo.start();
        botonIniciar.setEnabled(false);
        botonIniciar.setText("Reaunudar");
    }//GEN-LAST:event_botonIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FurbalandiaCronometroHombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FurbalandiaCronometroHombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FurbalandiaCronometroHombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FurbalandiaCronometroHombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FurbalandiaCronometroHombre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciar;
    private javax.swing.JLabel etiqueta_tiempo;
    private javax.swing.JLabel lWallPaper;
    // End of variables declaration//GEN-END:variables
}
