/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author fabri
 */
public class FurbalandiaNiño extends javax.swing.JFrame {

    int camino = 0;

    /**
     * Creates new form FurbalandiaNiño
     */
    public FurbalandiaNiño() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        camino1 = new javax.swing.JLabel();
        camino2 = new javax.swing.JLabel();
        camino3 = new javax.swing.JLabel();
        lWallPaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        camino1.setText(" ");
        camino1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        camino1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                camino1MouseClicked(evt);
            }
        });
        getContentPane().add(camino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 40, 40));

        camino2.setText(" ");
        camino2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        camino2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                camino2MouseClicked(evt);
            }
        });
        getContentPane().add(camino2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 40, 40));

        camino3.setText(" ");
        camino3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        camino3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                camino3MouseClicked(evt);
            }
        });
        getContentPane().add(camino3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 40, 40));

        lWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/InicioNiñoFurbalandia_1.png"))); // NOI18N
        lWallPaper.setText(" ");
        getContentPane().add(lWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void camino1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camino1MouseClicked
        // TODO add your handling code here:
        camino += 1;
    }//GEN-LAST:event_camino1MouseClicked

    private void camino2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camino2MouseClicked
        // TODO add your handling code here:
        camino += 1;
    }//GEN-LAST:event_camino2MouseClicked

    private void camino3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camino3MouseClicked
        // TODO add your handling code here:
        camino += 1;
        if (camino == 3) {
            FurbalandiaVideo fv = new FurbalandiaVideo();
            fv.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_camino3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FurbalandiaNiño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FurbalandiaNiño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FurbalandiaNiño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FurbalandiaNiño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FurbalandiaNiño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel camino1;
    private javax.swing.JLabel camino2;
    private javax.swing.JLabel camino3;
    private javax.swing.JLabel lWallPaper;
    // End of variables declaration//GEN-END:variables
}
