/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author fabri
 */
public class HormigolandiaIntegrantes extends javax.swing.JFrame {
    static String integrante1;
    static String integrante2;
    static String integrante3;
    static String integrante4;
    static String integrante5;
    /**
     * Creates new form HormigolandiaIntegrantes
     */
    public HormigolandiaIntegrantes() {
        initComponents();
        setLocationRelativeTo(null);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre5 = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        txtNombre3 = new javax.swing.JTextField();
        txtNombre4 = new javax.swing.JTextField();
        lSiguiente = new javax.swing.JLabel();
        lWallPaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 420, 40));
        getContentPane().add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 420, 40));
        getContentPane().add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 420, 40));
        getContentPane().add(txtNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 420, 40));
        getContentPane().add(txtNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 420, 40));

        lSiguiente.setText(" ");
        lSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSiguienteMouseClicked(evt);
            }
        });
        getContentPane().add(lSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 120, 130));

        lWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/integrantes.png"))); // NOI18N
        lWallPaper.setText(" ");
        getContentPane().add(lWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSiguienteMouseClicked
        // TODO add your handling code here:
        if (txtNombre3.getText().equals("") && txtNombre4.getText().equals("") 
                && txtNombre5.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tiene que ingresar mínimo 2 nombres"
                    + "", "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            integrante1=txtNombre1.getText();
            integrante2=txtNombre2.getText();
            integrante3=txtNombre3.getText();
            integrante4=txtNombre4.getText();
            integrante5=txtNombre5.getText();
            
            HormigolandiaActividades ha=new HormigolandiaActividades();
            ha.setVisible(true);
            this.dispose();
        }
        


    }//GEN-LAST:event_lSiguienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HormigolandiaIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HormigolandiaIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HormigolandiaIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HormigolandiaIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HormigolandiaIntegrantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lSiguiente;
    private javax.swing.JLabel lWallPaper;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtNombre3;
    private javax.swing.JTextField txtNombre4;
    private javax.swing.JTextField txtNombre5;
    // End of variables declaration//GEN-END:variables
}
