/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author fabri
 */
public class HormigolandiaActividades extends javax.swing.JFrame {

    Random numAleatorio = new Random();
    ArrayList<String> actividades = new ArrayList<>();
    ArrayList<Integer> indicesAleatoreas = new ArrayList<>();
    ArrayList<String> nombres = new ArrayList<>();

    /**
     * Creates new form HormigolandiaActividades
     */
    public HormigolandiaActividades() {
        initComponents();
        setTitle("Asignación de actividades");
        setResizable(false);
        setLocationRelativeTo(null);

        actividades.add("Barre tu cuarto");
        actividades.add("Tiende tu cama");
        actividades.add("Ordena tus juguetes");
        actividades.add("Arregla tu ropa");
        actividades.add("Limpia el polvo");

        nombres.add(HormigolandiaIntegrantes.integrante1);
        nombres.add(HormigolandiaIntegrantes.integrante2);
        nombres.add(HormigolandiaIntegrantes.integrante3);
        nombres.add(HormigolandiaIntegrantes.integrante4);
        nombres.add(HormigolandiaIntegrantes.integrante5);

        while (indicesAleatoreas.size() != 5) {
            int n = numAleatorio.nextInt(5);
            if (!indicesAleatoreas.contains(n)) {
                indicesAleatoreas.add(n);
            }
        }

        txtNombre1.setText(nombres.get(indicesAleatoreas.get(0)));
        txtActividad1.setText(actividades.get(indicesAleatoreas.get(0)));

        txtNombre2.setText(nombres.get(indicesAleatoreas.get(1)));
        txtActividad2.setText(actividades.get(indicesAleatoreas.get(1)));

        txtNombre3.setText(nombres.get(indicesAleatoreas.get(2)));
        txtActividad3.setText(actividades.get(indicesAleatoreas.get(2)));
        
        txtNombre4.setText(nombres.get(indicesAleatoreas.get(3)));
        txtActividad4.setText(actividades.get(indicesAleatoreas.get(3)));
    
        txtNombre5.setText(nombres.get(indicesAleatoreas.get(4)));
        txtActividad5.setText(actividades.get(indicesAleatoreas.get(4)));
        
        System.out.println(nombres);
        System.out.println(indicesAleatoreas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtActividad5 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JLabel();
        txtNombre3 = new javax.swing.JLabel();
        txtNombre4 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JLabel();
        txtActividad1 = new javax.swing.JLabel();
        txtActividad2 = new javax.swing.JLabel();
        txtActividad3 = new javax.swing.JLabel();
        txtActividad4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lWallPaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre5.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txtNombre5.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombre5.setText(" ");
        txtNombre5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 220, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Actividades");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 270, 50));

        txtActividad5.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txtActividad5.setForeground(new java.awt.Color(255, 255, 255));
        txtActividad5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtActividad5.setText(" ");
        txtActividad5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtActividad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 280, 50));

        txtNombre2.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txtNombre2.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombre2.setText(" ");
        txtNombre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 220, 50));

        txtNombre3.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txtNombre3.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombre3.setText(" ");
        txtNombre3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 220, 50));

        txtNombre4.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txtNombre4.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombre4.setText(" ");
        txtNombre4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 220, 50));

        txtNombre1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txtNombre1.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombre1.setText(" ");
        txtNombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 220, 50));

        txtActividad1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txtActividad1.setForeground(new java.awt.Color(255, 255, 255));
        txtActividad1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtActividad1.setText(" ");
        txtActividad1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtActividad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 280, 50));

        txtActividad2.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txtActividad2.setForeground(new java.awt.Color(255, 255, 255));
        txtActividad2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtActividad2.setText(" ");
        txtActividad2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtActividad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 280, 50));

        txtActividad3.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txtActividad3.setForeground(new java.awt.Color(255, 255, 255));
        txtActividad3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtActividad3.setText(" ");
        txtActividad3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtActividad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 280, 50));

        txtActividad4.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txtActividad4.setForeground(new java.awt.Color(255, 255, 255));
        txtActividad4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtActividad4.setText(" ");
        txtActividad4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtActividad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 280, 50));

        jLabel3.setText(" ");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 120, 130));

        lWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/actividadesHormigas.png"))); // NOI18N
        lWallPaper.setText(" ");
        lWallPaper.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        HomigaInfoTiempo hit=new HomigaInfoTiempo();
        hit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HormigolandiaActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HormigolandiaActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HormigolandiaActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HormigolandiaActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HormigolandiaActividades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lWallPaper;
    private javax.swing.JLabel txtActividad1;
    private javax.swing.JLabel txtActividad2;
    private javax.swing.JLabel txtActividad3;
    private javax.swing.JLabel txtActividad4;
    private javax.swing.JLabel txtActividad5;
    private javax.swing.JLabel txtNombre1;
    private javax.swing.JLabel txtNombre2;
    private javax.swing.JLabel txtNombre3;
    private javax.swing.JLabel txtNombre4;
    private javax.swing.JLabel txtNombre5;
    // End of variables declaration//GEN-END:variables
}
