/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author fabri
 */
public class MapaNiñaMundo1 extends javax.swing.JFrame {

    /**
     * Creates new form Mapa
     */
    public MapaNiñaMundo1() {
        initComponents();
        setTitle("Empezemos a jugar");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lMundo1 = new javax.swing.JLabel();
        lWallPaper = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lMundo1.setText(" ");
        lMundo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lMundo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMundo1MouseClicked(evt);
            }
        });
        getContentPane().add(lMundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 150, 180));

        lWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Portada Nivel 1 Niña.png"))); // NOI18N
        lWallPaper.setText(" ");
        getContentPane().add(lWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lMundo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMundo1MouseClicked
        // TODO add your handling code here:
        HormigolandiaNiñaActividad hna=new HormigolandiaNiñaActividad();
        hna.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lMundo1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapaNiñaMundo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapaNiñaMundo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapaNiñaMundo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapaNiñaMundo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapaNiñaMundo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lMundo1;
    private javax.swing.JLabel lWallPaper;
    // End of variables declaration//GEN-END:variables
}
