/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author fabri
 */
public class Personaje extends javax.swing.JFrame {

    static String nombre;
    static Boolean hombre=false;
    static Boolean mujer=false; 

    /**
     * Creates new form Personaje
     */
    public Personaje() {
        initComponents();
        setTitle("Elección del personaje");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNiña = new javax.swing.JButton();
        btnNiño = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lWallPaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNiña.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNiña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Niña.png"))); // NOI18N
        btnNiña.setText(" ");
        btnNiña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNiña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNiñaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNiña, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 230, 210));

        btnNiño.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNiño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Niño.png"))); // NOI18N
        btnNiño.setText(" ");
        btnNiño.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNiño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNiñoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 230, 210));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Escoje Personsaje");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel2.setText("Niño");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel3.setText("Niña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        lWallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/fondoJuego.png"))); // NOI18N
        lWallPaper.setText(" ");
        getContentPane().add(lWallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 697, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNiñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNiñoActionPerformed
        // TODO add your handling code here:
        nombre = JOptionPane.showInputDialog("¿Cuál es tu nombre?");
        hombre=true;
        MapaNiñoMundo1 mn=new MapaNiñoMundo1();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNiñoActionPerformed

    private void btnNiñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNiñaActionPerformed
        // TODO add your handling code here:
        nombre = JOptionPane.showInputDialog("¿Cuál es tu nombre?");
        mujer=true;
        MapaNiñaMundo1 mn = new MapaNiñaMundo1();
        mn.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnNiñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNiña;
    private javax.swing.JButton btnNiño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lWallPaper;
    // End of variables declaration//GEN-END:variables
}
